services:
  nginx:
    image: nginx:1.27.1-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/ssl:/etc/nginx/ssl
      - ./public/static:/var/www/static
    environment:
      - SERVER_NAME=localhost

  web:
    build:
      context: ./
      dockerfile: ./docker/django/Dockerfile
    
    volumes:
      - database:/var/database

volumes:
  database: