# Generated by Django 5.0.7 on 2024-07-11 01:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fw_block', '0003_protectednetworks'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='firewall',
            options={'permissions': (('can_block', 'Can block IPs'), ('can_unblock', 'Can unblock IPs'))},
        ),
        migrations.AlterModelOptions(
            name='ipaddress',
            options={'permissions': (('search_ipadress', 'Can search IPs'),)},
        ),
    ]
