# Generated by Django 5.0.7 on 2024-07-11 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fw_block', '0004_alter_firewall_options_alter_ipaddress_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ipaddress',
            name='asn',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
