# Generated by Django 5.0.7 on 2024-07-15 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fw_block', '0007_blockedlogs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blockedlogs',
            name='action',
            field=models.CharField(choices=[('block', 'Bloqueo'), ('unblock', 'Desbloqueo')], default='block', max_length=7),
        ),
    ]
