# Generated by Django 5.0.7 on 2024-07-16 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fw_block', '0009_alter_blockedlogs_options_alter_ipaddress_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='blockedlogs',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='blockedlogs',
            name='reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
