# Generated by Django 5.0.7 on 2024-08-20 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fw_block', '0010_blockedlogs_description_blockedlogs_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blockedlogs',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='blockedlogs',
            name='reason',
            field=models.TextField(blank=True, default=''),
        ),
    ]
